### PR TITLE
Update composer deps and ignore composer files

### PR DESCRIPTION
**Pull request by ejwaibel**
This commit should allow for proper composer install without errors.

### CODE REVIEW

**Comment by spawnia** [comment]
Ignoring `composer.lock` is an absolute anti-pattern and defies the whole idea behind it, we should absolutely keep it in the repository. Ignoring `composer.phar` is fair game.

Is there a reason for why we should use the development branch version of `phpunit` vs. simply changing to a newer version?

**Comment by craig-davis** [comment]
> is an absolute anti-pattern

Not much in the industry is absolute. I think in this case the project was being used as a dependency and the lock file was removed to ease some conflicts. This really started as an experiment, and it's grown into something much larger and more useful. I don't have a strong opinion about the lock file.

**Comment by spawnia** [comment]
You are making a good point here and you are right, commiting the lock file is not a necessity. After reading up on the recommendations in the [composer documentation](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control), i found that while it is strongly recommended for applications, it is less so for libraries.

So i guess it depends on what this project aims to be. If you think it will be used as a standalone tool, we should keep the lock file. On the other hand, if this project is likely to be used as a dependency in larger applications - then it might be helpful to remove the lock file to loosen the version constraints.

My opinion is that this project is most likely to be used on its own and because of this, it will be beneficial to have the dependencies tied down to a specific version.

**Comment by spawnia** [comment]
Closing due to the reasoning given above. This is more of a standalone tool, so we should nail down exact dependencies in composer.lock

**Pull request closed without merging**
